# Generated by Django 2.2.1 on 2019-05-13 03:57

import django.core.validators
from django.db import migrations, models
import unixtimestampfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SampleDataset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', unixtimestampfield.fields.UnixTimeStampField(auto_now_add=True)),
                ('updated_at', unixtimestampfield.fields.UnixTimeStampField(auto_now=True, auto_now_add=True)),
                ('deleted', models.BooleanField(default=False)),
                ('date', models.DateField()),
                ('channel', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=2)),
                ('os', models.CharField(max_length=10)),
                ('impressions', models.BigIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('clicks', models.BigIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('installs', models.PositiveIntegerField(default=0)),
                ('spend', models.DecimalField(decimal_places=2, max_digits=12)),
                ('revenue', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
            options={
                'ordering': ('id',),
                'abstract': False,
            },
        ),
    ]
